### ISSUE TITLE
Modal and useOverlayPosition

### ISSUE THREAD

**Issue by WildEgo** [GeekyAnts/react-native-aria#19]
Hi guys,
The problem I shown in my latest issue is also a problem here, but when using Modal it also adds a problem where my modal keeps over the overlay itself.
Maybe this could be fixed by using a third party Modal library, if that's the case have u guys tested it with any of them?

Thanks in advance,
Luis Bizarro.

**Comment by intergalacticspacehighway** [comment]
@WildEgo the Modal from RN always has a higher precedence. It'll always appear above any absolutely placed element. 
Can you use [OverlayContainer](https://react-native-aria.geekyants.com/docs/OverlayContainer) instead of RN's modal?
In NativeBase, to supports multiple Overlay items, we're using this OverlayContainer
https://react-native-aria.geekyants.com/docs/OverlayContainer

**Comment by WildEgo** [comment]
> @WildEgo the Modal from RN always has a higher precedence. It'll always appear above any absolutely placed element.
> Can you use [OverlayContainer](https://react-native-aria.geekyants.com/docs/OverlayContainer) instead of RN's modal?
> In NativeBase, to supports multiple Overlay items, we're using this OverlayContainer
> https://react-native-aria.geekyants.com/docs/OverlayContainer

I could do that if that's what you think is best, just write it somewhere in the docs so people can find it, I simply assumed it would plug and play (I'm RN Web and it seems to be rendering inside a div out of the main content and that seems to be why it's that way), that should also fix my problem with your popper library too.

**Comment by intergalacticspacehighway** [comment]
Sure, we'll update in the docs. Thanks for reporting :)
